######################################################################
# Automatically generated by qmake (2.01a) Di. Dez 18 20:08:03 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../src/AI/ki_logic.h ../src/Logic.h
SOURCES += main.cpp ../src/AI/ki_logic.cpp ../src/Logic.cpp
