######################################################################
# Automatically generated by qmake (2.01a) Do. Dez 6 18:16:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Logic.h server.h socket.h subServer.h
SOURCES += Logic.cpp main.cpp server.cpp socket.cpp subServer.cpp
