######################################################################
# Automatically generated by qmake (2.01a) Mo. Dez 3 23:12:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Logic.h server.h socket.h superserver.h
SOURCES += Logic.cpp main.cpp server.cpp socket.cpp superserver.cpp
