######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 5 14:10:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h socket.h
SOURCES += client.cpp main.cpp socket.cpp
