######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 12 23:26:36 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FieldItem.h revrsi.h TokenItem.h
FORMS += revrsi.ui
SOURCES += FieldItem.cpp main.cpp revrsi.cpp TokenItem.cpp
